apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: timer-client
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
      - www.pairprogrammingtimer.com
      secretName: timer-client-tls-secret-www
  rules:
  - host: www.pairprogrammingtimer.com
    http:
      paths:
        - path: /*
          backend:
            servicePort: 5000
            serviceName: timer-client-service

# ---

# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: timer-client
#   annotations:
#     kubernetes.io/ingress.class: "nginx"
#     nginx.ingress.kubernetes.io/use-regex: "true"
#     nginx.ingress.kubernetes.io/permanent-redirect: "https://www.pairprogrammingtimer.com"
# spec:
#   rules:
#   - host: pairprogrammingtimer.com
#     http:
#       paths:
#         - path: /*
#           backend:
#             servicePort: 5000
#             serviceName: timer-client-service
