apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: timer-client
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "7200"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "7200"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "7200"
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  tls:
    - secretName: timer-client-tls-secret
      hosts:
        - www.pairprogrammingtimer.com
        - pairprogrammingtimer.com
  rules:
    - host: www.pairprogrammingtimer.com
      http:
        paths:
          - path: /*
            backend:
              servicePort: 5000
              serviceName: timer-client-service
    - host: pairprogrammingtimer.com
      http:
        paths:
          - path: /*
            backend:
              servicePort: 5000
              serviceName: timer-client-service
